name: mistral_ai_chat_example_app
description: "Example app showcasing the Mistral AI chat client app."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ^3.16.0

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.4
  hooks_riverpod: ^2.4.9
  mistralai_client_dart:
    git:
      url: https://github.com/nomtek/mistralai_client_dart
      ref: 19-prepare-the-project-for-release-to-pubdev
  riverpod_annotation: ^2.3.3

dev_dependencies:
  build_runner: ^2.4.8
  custom_lint: ^0.5.8
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.3.9
  riverpod_lint: ^2.3.7
  test: ^1.24.9
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
