name: mistral_ai_chat_example_app
description: "Example app showcasing the Mistral AI chat client app."
publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ">=3.2.3 <4.0.0"
  flutter: ^3.16.0

dependencies:
  characters: ^1.3.0
  collection: ^1.18.0
  flutter:
    sdk: flutter
  go_router: ^13.0.1
  google_fonts: ^6.1.0
  json_annotation: ^4.8.1
  langchain: ^0.4.0
  material_symbols_icons: ^4.2718.0
  mistralai_client_dart: 0.0.2
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  
dev_dependencies:
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  go_router_builder: ^2.4.1
  json_serializable: ^6.7.1
  test: ^1.24.9
  very_good_analysis: ^5.1.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
